### ISSUE TITLE
Migrate to billing 5.0

### ISSUE THREAD

**Issue by newGenMobile** [wdtheprovider/in-app-purchase#1]
Are you planing on updating the code to billing 5.0?

Thanks, i appreciate your contributions.

**Comment by wdtheprovider** [comment]
Yes. I will be migrating it this coming weekend. Thank you for the heads up. Sent from my Huawei phone-------- Original message --------From: yahlamobile ***@***.***>Date: Sun, 28 Aug 2022, 18:29To: wdtheprovider/in-app-purchase ***@***.***>Cc: Subscribed ***@***.***>Subject: [wdtheprovider/in-app-purchase] Migrate to billing 5.0 (Issue #1)
Are you planing on updating the code to billing 5.0?
Thanks, i appreciate your contributions.

**Comment by wdtheprovider** [comment]
Done
